name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  e2e:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Test
        run: bash ./index.sh